// tokens.h
#define PROGRAM 1
#define BEGIN_KEYWORD 2
#define END 3
#define VAR 4
#define INTEGER_KEYWORD 5
#define REAL_KEYWORD 6
#define CHAR_KEYWORD 7
#define BOOLEAN_KEYWORD 8
#define IF 9
#define THEN 10
#define ELSE 11
#define WHILE 12
#define DO 13
#define FOR 14
#define TO 15
#define READ 16
#define WRITE 17
#define ASSIGN 18
#define STRING_LITERAL 19
#define IDENTIFIER 20
#define INTEGER 21
#define REAL 22
#define ADD 23
#define SUBTRACT 24
#define MULTIPLY 25
#define DIVIDE 26
#define MODULO 27
#define EQUALS 28
#define NOTEQUAL 29
#define LESS 30
#define GREATER 31
#define LESSEQUAL 32
#define GREATEREQUAL 33
#define SEMICOLON 34
#define COMMA 35
#define COLON 36
#define LPAREN 37
#define RPAREN 38
#define PERIOD 39
#define LBRAC 40
#define RBRAC 41